// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {model} from '../models';

export function GetUserConfig():Promise<backend.Config>;

export function PickFold():Promise<string>;

export function SaveUserConfig(arg1:backend.Config):Promise<void>;

export function TaskConfigToFrontInterface(arg1:model.TaskCfgFrontInterface):Promise<void>;
